version: 2
jobs:
  build:
    docker:
      image: iganarix/base-alpine
    steps:
      - checkout
      - run:
        name: Hello World TEST
        command: 'Hello World !!!'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
      - test:
          requires:
            - build
          filters:
            branches:
              only: modify-readme-only 
        
