version: 2
jobs:
  build:
    docker:
      - image: iganarix/base-alpine
    steps:
      - checkout
      - run:
          name: Hello World TEST
          command: "echo 'Hello World !!!'"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: feature/add-circleci
        
