kind: Pod
apiVersion: v1
metadata:
  name: apple-app
  labels:
    app: apple
spec:
  containers:
    - name: apple-app
      image: hashicorp/http-echo  # https://hub.docker.com/r/hashicorp/http-echo/
      args:
        - "-text=apple"