apiVersion: v1
kind: Service
metadata:
  name: banana-service
spec:
  type: NodePort
  selector:
    app: banana
  ports:
    - protocol: TCP
      port: 5678 # default port -> refs: https://hub.docker.com/r/hashicorp/http-echo/
