apiVersion: v1
kind: Service
metadata:
  name: my-serv
  labels:
    app.kubernetes.io/name: load-balancer-example
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: load-balancer-example
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
