apiVersion: v1
kind: Service
metadata:
  name: load-balancer-example
spec:
  type: LoadBalancer
  selector:
    app: load-balacer-example
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
