## https://github.com/kubernetes/examples/blob/master/guestbook/redis-slave-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  namespace: sample_guestbook
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  ports:
  - port: 6379
  selector:
    app: redis
    role: slave
    tier: backend
