# https://gist.github.com/iganari/e79f80cd13340642913418a3b1ec16f5

name: Pull Master Branch on modify-readme-only Branch

on:
  push:
    branchs:
      - master
      - feature/add-actions-yaml # For test branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: modify-readme-only
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: ls && pwd && which git && git status && git branch -a && git remote -v && git checkout modify-readme-only
    - name: Run a multi-line script
      env:
        SECRET_VARIABLE: ${{ secrets.VAR_TEST }}
      run: |
        git status
        git branch -a
        git checkout modify-readme-only
        git status
