# https://gist.github.com/iganari/e79f80cd13340642913418a3b1ec16f5

name: Pull Master Branch on modify-readme-only Branch

on:
  push:
    branchs:
      - master
      - feature/add-actions-yaml # For test branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: modify-readme-only
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      env:
        SECRET_VARIABLE: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo ${SECRET_VARIABLE}
        echo ${GITHUB_TOKEN}
        echo ${GITHUB_SHA}
        
