# https://gist.github.com/iganari/e79f80cd13340642913418a3b1ec16f5

name: Pull Master Branch on modify-readme-only Branch

on:
  push:
    branchs:
      - master
      - feature/add-actions-yaml # For test branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: some-branch
      run: ls
    # - uses: actions/checkout@v1
    # - name: Run a one-line script
    #   run: ls && pwd && which git && git status && git remote -v
    - name: Run a multi-line script
      env:
        SECRET_VARIABLE: ${{ secrets.VAR_TEST }}
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo ${VAR_TEST}
