# https://gist.github.com/iganari/e79f80cd13340642913418a3b1ec16f5

name: Pull Master Branch on modify-readme-only Branch

on:
  push:
    branchs:
      - master
      - feature/add-actions-yaml # For test branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: modify-readme-only

    - name: clone
      env:
        SECRET_VARIABLE: ${{ secrets.user_email }}
      run: |
        # pwd
        # git clone https://github.com/iganari/package-kubernetes.git /tmp/package-kubernetes
        # cd /tmp/package-kubernetes
        ls
        # git checkout modify-readme-only
        git status
        git config --global user.name "iganari"
        git config --global user.email "${user_email}"
        git config -l
        git merge origin master -m "Pull Master Branch on modify-readme-only Branch"
        
    - name: Deploy
      env:
        DEPLOY_KEY: ${{ secrets.githubactions_pkg_k8s }}
      run: |
        git status
        git branch -a
        touch /tmp/id_rsa
        chmod 0700 /tmp/id_rsa
        echo ${DEPLOY_KEY} > /tmp/id_rsa
        sh ${GITHUB_WORKSPACE}/test.sh
