# https://gist.github.com/iganari/e79f80cd13340642913418a3b1ec16f5

name: Pull Master Branch on modify-readme-only Branch

on:
  push:
    branchs:
      - master
      - feature/add-actions-yaml # For test branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: modify-readme-only

    - name: clone 
      run: |
        git clone https://github.com/iganari/package-kubernetes.git /tmp/package-kubernetes
        cd /tmp/package-kubernetes
        ls
        
